### ISSUE TITLE
sandboxUrl

### ISSUE THREAD

**Issue by ohadraz** [wix/libpay-dlocal#3]
DLocalGatewaySettings includes a member, named sandboxUrl.
It is not clear why there's a need for this member, on prod. code.
The Sandbox's URL can be populated in the `url` member, in the tests (not unit/IT tests, as those should not issue external HTTP calls, but for some nightly/weekly builds, on a separate repo.)
Kindly explain, as this change breaks pay-direct.

**Comment by ymakhno** [comment]
@ohadraz change allows to connect sandbox accounts on production system, this is needed during development as well as automated QA flow and support sandbox accounts together with production ones is our strategy.

pay-direct build is fixed
